###
POST http://localhost:8080/api/example4/register
Content-Type: application/json

{
  "name": "GT",
  "password": "190514"
}

###
POST http://localhost:8080/api/example4/login
Content-Type: application/json

{
  "name": "GT",
  "password": "190515"
}

###
